disabled_rules: # rule identifiers to exclude from running
  - todo
  - operator_whitespace
  - large_tuple
  - closure_parameter_position
included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
  - Sources
  - Tests
excluded: # paths to ignore during linting. overridden by `included`.

identifier_name:
  excluded:
    - db
    - to
    - by
    - or
    - eq
    - gt
    - lt
    - fn
    - a
    - b

line_length:
  warning: 150
  error: 150
  ignores_comments: true


file_length:
  warning: 700
  error: 700
